[stats.merge_corpus_timer]
secs = 2
nanos = 0

[stats.stats_sync_timer]
secs = 0
nanos = 500000000

[stats.coverage_sync_timer]
secs = 2
nanos = 0

[redqueen]
entropy_threshold = 8
cores = 10
mutate_by_redqueen_rules = false
